# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c3392664862056aae58156206cd719a7"
name = "Validation (order limit) - dev"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "purple-owl-store-dev.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
